M48
; DRILL file {KiCad (6.0.9)} date Fri Jan 27 21:22:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-27T21:22:42-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X1.8804Y-1.5341
X2.6245Y-0.8716
X4.6179Y-1.5341
X4.6279Y-0.4028
T0
M30
