M48
; DRILL file {KiCad (6.0.9)} date Fri Jan  6 21:16:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-06T21:16:05-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0551
%
G90
G05
T1
X6.147Y-4.263
T2
X5.71Y-3.3146
X5.71Y-3.48
X5.9265Y-3.3146
X5.9265Y-3.48
T0
M30
