M48
; DRILL file {KiCad 7.0.2} date Wed May 17 01:37:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-17T01:37:15-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.3266Y1.835
X0.3266Y0.9689
T2
X0.5425Y1.9291
X0.5425Y0.0787
X2.0386Y1.9291
X2.0386Y0.0787
T0
M30
