M48
; DRILL file {KiCad (6.0.9)} date Tue Jan 10 01:38:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-10T01:38:09-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X0.931Y-3.42
X1.2283Y-3.42
X1.997Y-3.42
X2.283Y-3.42
T2
X0.1273Y-3.566
X0.142Y-0.13
X3.5913Y-0.134
X3.614Y-3.5627
T0
M30
