M48
; DRILL file {KiCad (6.0.9)} date Sat Jan 21 09:36:01 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-21T09:36:01-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X0.1181Y-2.5591
X0.872Y-0.4962
X1.7323Y-0.1181
X1.7323Y-2.5591
T0
M30
