M48
; DRILL file {KiCad (6.0.9)} date Fri Jan  6 20:59:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-06T20:59:09-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1406
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.5000
%
G90
G05
T1
X5.8012Y-3.1639
T2
X3.5512Y-2.0339
X7.8012Y-2.0339
T3
X5.8012Y-2.7889
X5.8012Y-2.7889
T0
M30
