M48
; DRILL file {KiCad 7.0.2} date Fri May  5 17:07:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-05T17:07:05-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.5000
%
G90
G05
T1
X5.4994Y-1.5094
X5.8744Y-6.8844
T2
X5.2994Y-6.6094
T0
M30
