M48
; DRILL file {KiCad 7.0.1} date Wed Apr 12 19:10:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-12T19:10:25-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.5000
%
G90
G05
T1
X5.985Y-5.388
X6.885Y-2.098
T2
X6.185Y-3.348
X6.6225Y-5.6605
X7.225Y-3.348
T0
M30
