M48
; DRILL file {KiCad 7.0.1} date Wed Dec 13 18:35:55 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-13T18:35:55-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.165Y0.3528
X2.365Y0.9516
X3.0311Y0.3528
X3.0657Y0.9516
T2
X0.125Y0.1
X0.175Y2.0
X3.125Y2.0
X3.375Y0.1
T0
M30
