M48
; DRILL file {KiCad 7.0.2} date Sun May 21 12:24:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-21T12:24:47-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1406
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.5000
%
G90
G05
T1
X5.297Y-3.6075
T2
X4.682Y-4.6325
X5.812Y-3.1525
T3
X5.297Y-3.9825
T0
M30
