name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type: Bug/Obsolesce", "Triage Required"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! OpenHornet lives on its community contributions and reports!
  - type: input
    id: contact
    attributes:
      label: Discord Username
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Noctum#4085
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Please summarize your issue here. Be as specific as possible.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes: 
      label: Expected Results
      description: What did you expect to happen?
      placeholder: Be very specific. The more detail, the better we can analyze the issue.
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes: 
      label: Actual Results
      description: What actually happened?
      placeholder: Be very specific. The more detail, the better we can analyze the issue.
    validations:
      required: true
  - type: textarea
    id: images
    attributes: 
      label: Screenshots/Images/Files
      description: Pictures/Files are worth 1000 words. Take some screen grab of the model, circle things with the snipping tool, put together a quick power point description of the issue, drop in a STEP/F3Z file of a fix you made - you can't put too much information here!
      placeholder: You can just paste images or files in this field...
    validations:
      required: false
  - type: input
    id: part-numbers
    attributes:
      label: Applicable Part Numbers
      description: List the part number(s) this issue applies to.
      placeholder: ex. OH02A5-136, OH04A2-1, etc.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Release Version
      description: What release are you building to?
      options:
        - v0.2.0
        - pre-v0.2.0 (Early Development/Alpha)
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Is this a mechanical and/or electrical issue or artwork? Mechanical being physical parts like structure, seat, mechanisms, etc. Electrical would be PCBs, wiring, etc. Artwork would be placards, stickers, dataplates or a vector art issue. (You may select more than one.) 
      multiple: true
      options:
        - Mechanical (Structure/Panels/Mechanisms)
        - Electrical (PCBs/Wiring/etc)
        - Artwork (Decals)
    validations:
        required: true
  - type: dropdown
    id: end-item
    attributes:
      label: Applicable End Item(s)
      description: What End Item(s) does this issue apply to? 
      multiple: true
      options:
        - Top Level Assembly (TLA)
        - Upper Instrument Panel (UIP)
        - Lower Instrument Panel (LIP)
        - Center Tub (CT)
        - Left Console (LCON)
        - Right Console (RCON)
        - Flight Stick
        - Throttle
    validations:
        required: true
  - type: checkboxes
    id: built-to-print
    attributes:
      label: Built to print?
      description: Did you build this part to the relevant drawing, using parts specified by OpenHornet? (It's okay if you didn't, just describe how you deviated in the Miscellaneous Info text area below.)
      options:
        - label: I built (or attempted to build) the part to the OpenHornet print without any deviations.
        - label: I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)
          required: false
  - type: textarea
    id: misc
    attributes: 
      label: Miscellaneous Info
      description: Do you have any additional information not previously covered?
      placeholder: This space would be to provide specific applicable model names and versions, deviations from the OpenHornet build, or provide any information that is not covered elsewhere in this report.
    validations:
      required: false
