M48
; DRILL file {KiCad (6.0.9)} date Mon Jan  9 23:31:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-09T23:31:45-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X0.3543Y-0.1181
X0.3543Y-0.6693
X0.6693Y-0.1181
X0.6693Y-0.6693
T0
M30
