M48
; DRILL file {KiCad (6.0.9)} date Fri Jan 27 20:31:41 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-27T20:31:41-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1772
%
G90
G05
T1
X6.14Y-1.6825
X6.14Y-5.4775
X6.51Y-1.6825
X6.51Y-5.4775
T2
X2.925Y-1.515
X2.925Y-5.765
X8.925Y-1.515
X8.925Y-5.765
T0
M30
