M48
; DRILL file {KiCad (6.0.9)} date Fri Jan  6 20:53:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-06T20:53:46-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.5000
%
G90
G05
T1
X1.591Y-4.952
X5.051Y-5.5145
T2
X2.276Y-5.3142
X2.276Y-5.3142
X4.026Y-5.307
X4.026Y-5.307
X5.776Y-5.307
X5.776Y-5.307
T0
M30
