M48
; DRILL file {KiCad (6.0.9)} date Mon Dec 26 19:41:24 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-26T19:41:24-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0937
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.2969
%
G90
G05
T1
X4.5575Y-3.4756
T2
X4.5659Y-5.4331
X4.5669Y-4.4094
X6.9281Y-5.4341
X6.9301Y-4.4094
T3
X4.5575Y-3.7118
X4.5575Y-3.7118
T0
M30
