M48
; DRILL file {KiCad 7.0.2} date Sun May 14 20:04:02 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-14T20:04:02-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X2.165Y0.3528
X2.365Y0.9516
X3.0311Y0.3528
X3.0657Y0.9516
T2
X0.125Y0.1
X0.175Y2.0
X3.125Y2.0
X3.375Y0.1
T0
M30
