M48
; DRILL file {KiCad 7.0.1} date Wed Apr  3 18:52:35 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-03T18:52:35-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X0.0394Y-0.1181
T2
X-0.2362Y0.4331
X0.2362Y-0.4331
T0
M30
