M48
; DRILL file {KiCad (6.0.9)} date Fri Jan 27 23:50:43 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-27T23:50:43-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X4.1614Y-3.3465
X4.5Y-3.3465
T2
X3.9567Y-3.7205
X4.7047Y-2.9724
T0
M30
