M48
; DRILL file {KiCad (6.0.9)} date Fri Jan  6 21:10:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-06T21:10:05-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1406
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.5000
%
G90
G05
T1
X4.61Y-3.245
X5.61Y-2.87
T2
X3.31Y-2.995
X6.74Y-3.295
X8.36Y-2.92
T3
X4.235Y-3.245
X4.235Y-3.245
X5.61Y-3.245
X5.61Y-3.245
T0
M30
