M48
; DRILL file KiCad 10.0.3 date 2026-09-09T12:19:41
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-09T12:19:41+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.2516Y1.285
X0.2516Y0.2535
T2
X0.6Y2.0
X3.55Y2.0
X3.8Y0.1
M30
